package com.example.pfinance.ui.theme

import androidx.compose.ui.graphics.Color

// Light theme colors
val md_theme_light_primary = Color(0xFF386A20)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFB7F397)
val md_theme_light_onPrimaryContainer = Color(0xFF052100)
val md_theme_light_secondary = Color(0xFF54634D)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD8E8CC)
val md_theme_light_onSecondaryContainer = Color(0xFF131F0E)
val md_theme_light_tertiary = Color(0xFF386667)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFBCECED)
val md_theme_light_onTertiaryContainer = Color(0xFF002021)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF8FBF0)
val md_theme_light_onBackground = Color(0xFF1A1C18)
val md_theme_light_surface = Color(0xFFF8FBF0)
val md_theme_light_onSurface = Color(0xFF1A1C18)
val md_theme_light_surfaceVariant = Color(0xFFE0E4D7)
val md_theme_light_onSurfaceVariant = Color(0xFF43483E)
val md_theme_light_outline = Color(0xFF73796D)
val md_theme_light_inverseSurface = Color(0xFF2F312D)
val md_theme_light_inverseOnSurface = Color(0xFFF0F2E7)
val md_theme_light_inversePrimary = Color(0xFF9CD67E)
val md_theme_light_surfaceTint = Color(0xFF386A20)

// Dark theme colors
val md_theme_dark_primary = Color(0xFF9CD67E)
val md_theme_dark_onPrimary = Color(0xFF0E3900)
val md_theme_dark_primaryContainer = Color(0xFF215106)
val md_theme_dark_onPrimaryContainer = Color(0xFFB7F397)
val md_theme_dark_secondary = Color(0xFFBCCCB1)
val md_theme_dark_onSecondary = Color(0xFF273422)
val md_theme_dark_secondaryContainer = Color(0xFF3D4B37)
val md_theme_dark_onSecondaryContainer = Color(0xFFD8E8CC)
val md_theme_dark_tertiary = Color(0xFFA0CFD1)
val md_theme_dark_onTertiary = Color(0xFF003738)
val md_theme_dark_tertiaryContainer = Color(0xFF1E4E4F)
val md_theme_dark_onTertiaryContainer = Color(0xFFBCECED)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1A1C18)
val md_theme_dark_onBackground = Color(0xFFE2E3DB)
val md_theme_dark_surface = Color(0xFF1A1C18)
val md_theme_dark_onSurface = Color(0xFFE2E3DB)
val md_theme_dark_surfaceVariant = Color(0xFF43483E)
val md_theme_dark_onSurfaceVariant = Color(0xFFC3C8BA)
val md_theme_dark_outline = Color(0xFF8D9285)
val md_theme_dark_inverseSurface = Color(0xFFE2E3DB)
val md_theme_dark_inverseOnSurface = Color(0xFF2F312D)
val md_theme_dark_inversePrimary = Color(0xFF386A20)
val md_theme_dark_surfaceTint = Color(0xFF9CD67E)

// Income/Expense colors
val IncomeGreen = Color(0xFF4CAF50)
val ExpenseRed = Color(0xFFE53935)
val TransferBlue = Color(0xFF2196F3)
